name: hive_built_value_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 2.3.0
homepage: https://github.com/hivedb/hive/tree/master/hive_flutter
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive_built_value:
    path: ../hive_built_value
  path_provider: ^2.0.14
  path: ^1.8.2

dev_dependencies:
  test: ^1.24.2
  lints: ^2.0.1
  mockito: ^5.4.0
  build_runner: ^2.3.3

dependency_overrides:
  meta: ^1.8.0